### ISSUE TITLE
Aesthetic issues, Organization, License Terms link and MS Store

### ISSUE THREAD

**Issue by Gaoyifei1011** [dongle-the-gadget/WinverUWP#1]
1. Hope to upgrade the background color of the three buttons in the upper right corner to Windows 11 style button format (minimize, maximize and close).
![屏幕截图 2021-11-22 231307](https://user-images.githubusercontent.com/49179966/142888045-50aecaec-fb14-459f-a5b4-5c869c05cc56.png)
![image](https://user-images.githubusercontent.com/49179966/142888251-49196ae2-ab3d-4977-9846-dbd976e7a1b4.png)

2. It seems that Winver contains Microsoft software license terms. We hope that the content of this piece can be added in the future version or a hyperlink can be provided to open the content of this piece (after all, it is included in Winver).
![image](https://user-images.githubusercontent.com/49179966/142888714-cc6d1611-b4ae-46e9-90a3-1e7c8af21e21.png)

3. Winver seems to have organization names, but WinverUWP has not been added

4. I hope I can upgrade the ICONS of WinverUWP, the ICONS in the taskbar and start button are too small.You want to remove the background image and save a larger logo icon=
![image](https://user-images.githubusercontent.com/49179966/142889118-4607b9de-9d43-45f7-9145-de93e180e3fc.png)
![image](https://user-images.githubusercontent.com/49179966/142889164-8f2b3d3e-0cf3-47d9-8e02-356567a9d805.png)

5. I hope that the future versions will be available in the Microsoft Store

**Comment by dongle-the-gadget** [comment]
I think that the background in the app list entry is behavior of UWP apps.

**Comment by dongle-the-gadget** [comment]
> It seems that Winver contains Microsoft software license terms. We hope that the content of this piece can be added in the future version or a hyperlink can be provided to open the content of this piece (after all, it is included in Winver).

That might require me to make changes to localization.

**Comment by dongle-the-gadget** [comment]
> Hope to upgrade the background color of the three buttons in the upper right corner to Windows 11 style button format (minimize, maximize and close).

Huh, never had this problem on my local machine.
![image](https://user-images.githubusercontent.com/29563098/142953546-7b5c9c57-dad7-43a4-860e-9786a2bd8aec.png)

(Yeah excuse the language since this is a version with pseudolocalization)

**Comment by dongle-the-gadget** [comment]
> I hope that the future versions will be available in the Microsoft Store

Yeah me too, but currently I don't have a developer account.

**Comment by dongle-the-gadget** [comment]
> Winver seems to have organization names, but WinverUWP has not been added

Huh. That might be a buggy implementation since I did remember to add org name.

**Comment by Gaoyifei1011** [comment]
> > Hope to upgrade the background color of the three buttons in the upper right corner to Windows 11 style button format (minimize, maximize and close).
> 
> Huh, never had this problem on my local machine. ![image](https://user-images.githubusercontent.com/29563098/142953546-7b5c9c57-dad7-43a4-860e-9786a2bd8aec.png)
> 
> (Yeah excuse the language since this is a version with pseudolocalization)

这个关于标题栏颜色bug的发生条件是在设置->个性化->颜色中开启”在标题栏和窗口边框上显示强调色“这一选项后，WinverUWP窗口处于非活动窗口后发生的
The title bar color bug occurs when a WinverUWP window is in an inactive window after the "highlight color" option is turned on in Settings -> Preferences -> Colors

在白色主题界面中也出现了这样的bug
This bug also appears in the white theme interface

![image](https://user-images.githubusercontent.com/49179966/142970180-1a925099-2937-4ae7-9a11-fd0c2e49471e.png)
![image](https://user-images.githubusercontent.com/49179966/142970190-5dfa6808-f96e-4700-9719-8eea3a35d7ef.png)

**Comment by dongle-the-gadget** [comment]
> > > Hope to upgrade the background color of the three buttons in the upper right corner to Windows 11 style button format (minimize, maximize and close).
> >
> > Huh, never had this problem on my local machine.
> 
> The title bar color bug occurs when a WinverUWP window is in an inactive window after the "highlight color" option is turned on in Settings -> Preferences -> Colors

Yeah. I think that's an interesting use case which I don't think Microsoft's documentation assumed people would have used.

**Comment by dongle-the-gadget** [comment]
@Gaoyifei1011 the title bar bug should now be fixed in acf54a7.

**Comment by dongle-the-gadget** [comment]
Due to some issues happening right now with Release 1.0.1, I will release version 1.1 now, with the title bar bug. Other issues would be pushed to fix later.

**Comment by Gaoyifei1011** [comment]
> Due to some issues happening right now with Release 1.0.1, I will release version 1.1 now, with the fix for the title bar bug. Other issues would be pushed to fix later.
 
Thanks for your reply.
感谢您的回复。

I have updated to version 1.1 yesterday, and I have submitted the bug feedback of version 1.1. Please go to the bug feedback page of 1.1.
我昨天已经更新到了1.1版本，我已经提交了1.1版本的bug反馈，请移步1.1的bug反馈页面。

![image](https://user-images.githubusercontent.com/49179966/143466399-c85a0971-e3a2-44cd-9f8d-d23e3e73baad.png)

**Comment by dongle-the-gadget** [comment]
I'll just close this for #8
