### ISSUE TITLE
hope to upgrade Windows sdk version

### ISSUE THREAD

**Issue by Gaoyifei1011** [dongle-the-gadget/WinverUWP#13]
希望能够升级一下Windows sdk 版本，目前这个项目好像使用的是Windows sdk 10.0.17134.0，希望能够升级一下这个sdk版本，在最新的visual studio 2022中都已经不再默认提供Windows sdk 10.0.17134.0了，最低的版本是Windows sdk 10.0.18362.0，如果未来版本采用Windows sdk 10.0.19041.0版本构建（目前的Windows LTSC）是不是效果更好呢？

I hope to upgrade the Windows SDK version. At present, the project seems to be using Windows SDK 10.0.17134.0. I hope to upgrade this SDK version. Windows SDK 10.0.17134.0 is no longer available by default in Visual Studio 2022. The lowest version is Windows SDK 10.0.18362.0. Wouldn't it be better if future versions were built with Windows SDK 10.0.19041.0 (the current Windows LTSC)?

![image](https://user-images.githubusercontent.com/49179966/147487322-c3872b9f-ba0d-416a-819e-4c8fd4659a3a.png)

**Comment by dongle-the-gadget** [comment]
I leave the min SDK to that to support people running 1809, you can upgrade it if you want to, but just keep 1809 SDK support in mind.
