### ISSUE TITLE
Experience field returns nothing on stable builds (2.0)

### ISSUE THREAD

**Issue by Gaoyifei1011** [dongle-the-gadget/WinverUWP#23]
The experience under "Windows specifications "works fine on preview OS 22526, but not on official OS 19044, 22000.
![image](https://user-images.githubusercontent.com/49179966/148794902-3277ab3a-b2c2-4769-bfe2-941343d03144.png)
The first application is the display under system 19044, the second application is the original version 1.1 (system 19044), and the third application is the display under system 22000.

**Comment by dongle-the-gadget** [comment]
`ProductName` isn't actually the same as WIM's `Caption` member, hence they return different results.

**Comment by dongle-the-gadget** [comment]
I could try using App Diagnostics, which might be more accurate, however will require using a restricted capability (not my desire since a rescap can slow down store submissions)

**Comment by dongle-the-gadget** [comment]
I saw this screenshot from WC Discord Server and it indicates no problem displaying the field in 22000.376
![image](https://user-images.githubusercontent.com/29563098/148860896-405dcdfc-d5b0-4dc7-bad7-d34580d1e7e8.png)

**Comment by dongle-the-gadget** [comment]
Also you can please not repost stuff already filed in other issues, thanks.

**Comment by dongle-the-gadget** [comment]
Also can you please not repost stuff already filed in other issues, thanks.

**Comment by dongle-the-gadget** [comment]
Also the fields shouldn't be blank like that.

**Comment by Gaoyifei1011** [comment]
> Also can you please not repost stuff already filed in other issues, thanks.

关于这个，我会注意的。重复提交相同的问题，我会认真检查的。给您和您的团队造成了不便，抱歉。
I'll keep an eye on that. Submit the same questions repeatedly and I will check them carefully. Sorry for the inconvenience caused to you and your team.

**Comment by dongle-the-gadget** [comment]
Couldn't replicate this on my Windows 10 19044 VM.
![](https://user-images.githubusercontent.com/29563098/149312291-71b87d98-408b-44c7-873d-1a5d313651aa.png)

**Comment by dongle-the-gadget** [comment]
Left Store, Right latest commits
![](https://user-images.githubusercontent.com/29563098/149313608-1ef12d02-90e7-4ad5-9bfe-88b0d1325f22.png)

**Comment by CuteCry** [comment]
So I take it this is fixed? When can we expect a Store update?
