### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by MuhammetEminCakir** [dongle-the-gadget/WinverUWP#37]
Although the system language is Turkish, the application is in another language. 
Even if the application does not work in Turkish, i would like it to be in English
![resim](https://user-images.githubusercontent.com/64583157/181794766-1bbfb99e-8d78-46e9-ae5e-fe4ef3cc537b.png)

**Comment by dongle-the-gadget** [comment]
Yeah, this is a bug.

WinverUWP doesn't support any language in your language list, so it fallbacks to the first language defined in the manifest (which for the Store version is Korean).

**Comment by AlperAkca79** [comment]
Hello @dongle-the-gadget. I can help you to translate If WinverUWP project still don't have Turkish language support.

**Comment by dongle-the-gadget** [comment]
I still haven't finalized the current version, so I won't be accepting translation requests as of right now.

**Comment by AlperAkca79** [comment]
I can help you when you are finalized the current version.
