### ISSUE TITLE
Allow to copy only the Windows version

### ISSUE THREAD

**Issue by MarcAnt01** [dongle-the-gadget/WinverUWP#38]
For bug reports on GitHub I need to copy the Windows version number (OS build parameter), but I would like to be able to copy only it and not the additional information

**Comment by dongle-the-gadget** [comment]
I thought you can already select the OS build field separately?

**Comment by MarcAnt01** [comment]
No, the text is not selectable

**Comment by MarcAnt01** [comment]
I guess this can be closed, then?
