### ISSUE TITLE
WinverUWP has a different language even though my OS is English

### ISSUE THREAD

**Issue by slideglide** [dongle-the-gadget/WinverUWP#52]
![image](https://github.com/dongle-the-gadget/WinverUWP/assets/68702247/a8f5995f-10cd-466c-a98c-4ee075e21382)

**Comment by dongle-the-gadget** [comment]
This issue has been fixed upstream, but the version on Store hasn't been fixed yet.

**Comment by dongle-the-gadget** [comment]
Store should be updated now
