### ISSUE TITLE
Problems encountered after version 1.1 upgrade and hope to be improved in the future

### ISSUE THREAD

**Issue by Gaoyifei1011** [dongle-the-gadget/WinverUWP#8]
Problems encountered after version 1.1 upgrade and hope to be improved in the future
1.1版本升级后的遇到的问题和希望未来得到的改进

Thank you very much for fixing the bug and releasing version 1.1 quickly, but I encountered other problems in version 1.1 after upgrading, I hope the developers can fix these bugs as soon as possible.
非常感谢开发者您能够很快的修复bug并快速的发布1.1版本，但是我在升级之后在1.1版本中又遇到了其他问题，希望开发者能尽快修复这些bug。

1.应用界面的体验部分显示异常
The experience part of the application page is displayed abnormally

如图所示，体验部分显示了一些奇怪的字符串。
As you can see, the experience section shows some strange strings.

Strange things that come up.
出现的奇怪的内容。

Windows Feature Experience Pack Get-AppxPackage: The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'.
![image](https://user-images.githubusercontent.com/49179966/143467127-9fbac19e-956a-4a46-8743-45c4273b3b29.png)

2.希望未来的版本能够添加更多语言支持，例如简体中文（zh_CN），繁体中文（zh_TW）等。
Hope to add more language support in future versions, such as Simplified Chinese (zh_CN), traditional Chinese (zh_TW), etc.

3.希望能够简化一下功能模块，应用安装包及安装文件太大了。
Hope to simplify the function module, the application installation package and installation file is too large.
![image](https://user-images.githubusercontent.com/49179966/143467659-3b24c0db-a705-4043-aa32-da8dee2b1d2f.png)

4.希望未来的版本中能够制作一个更优雅的图标。目前应用图标在任务栏中显示的非常小，而且我个人认为边界的紫色框没有必要存在，希望接下来的版本中能够制作一个更大的图标，并只保留蓝色logo大图标，去除掉紫色任务栏边框（个人看法）
Hopefully a more elegant icon will be made in future versions.Currently, the app icon is displayed very small in the taskbar, and I personally think the purple border is unnecessary. I hope that in the next version, we can make a bigger icon and only keep the blue logo, and remove the purple taskbar border (my opinion).
![image](https://user-images.githubusercontent.com/49179966/143468026-7f8afa86-0931-4ab3-b249-048c15dc0e6b.png)

**Comment by dongle-the-gadget** [comment]
The experience is due to for whatever reason, Appx module from PowerShell isn't loaded by default.

**Comment by dongle-the-gadget** [comment]
> Hope to add more language support in future versions, such as Simplified Chinese (zh_CN), traditional Chinese (zh_TW), etc.

Currently have to rely on PR translations as idk CHinese.

**Comment by dongle-the-gadget** [comment]
Well for the Experience bug, idk what caused it since last version worked for you and I did not modify anything related to Experience except from localizing the text "Windows Feature Experience Pack".

I could try to mitigate it by checking if it throws an error, and if it does I will say "Experience unknown"

**Comment by Gaoyifei1011** [comment]
> ce is due to for whatever reason, Appx module from PowerShell isn't loaded by default. This application uses powershell.exe which on a normal install of Windows would have the APPX module loaded.
> The only thing that comes to mind for me is that Windows PowerShell might be mapped to use PowerShell Core (version earlier than 7.2.0), which doesn't have APPX loaded by default.

是的的确如此。我已经查找出来这个bug是怎么发生的了。之前我尝试了一下将powershell重定向到msix版本的powershell core，就发生了这样的bug，删除了相应的注册表设置后就能够正常运行了。
Yes, indeed.I have found out how this bug happened.I tried redirecting Powershell to the MSIX version of Powershell Core, and this bug happened. I removed the registry Settings and it worked fine.

**Comment by Gaoyifei1011** [comment]
> 

也许你可能对简体中文翻译存在困难，我将在月底，也就是2022年帮助你翻译到简体中文。抱歉，目前我要准备研究生考试（中国大陆时间2021年12月25日和26日），没有充足的时间来帮助你翻译更多的语言。
Maybe you have trouble translating into Simplified Chinese, I will help you translate into simplified Chinese by the end of the month, in 2022.Sorry, at present I have to prepare for the postgraduate examination (December 25 and 26, 2021, Chinese mainland time), so I don't have enough time to help you translate more languages.

**Comment by Gaoyifei1011** [comment]
这是我对这个应用的新的期望
That's my new expectation for this application

![图片](https://user-images.githubusercontent.com/49179966/144626787-766b7c28-21e9-4f4f-94c0-e78407caaf6b.png)
如果Windows 11的logo图标能够带有颜色（比如微软Windows 11的渐变蓝色）就更加美观了。
It would be nice if the Windows 11 logo icon had a color (such as Microsoft Windows 11's gradient blue).

![图片](https://user-images.githubusercontent.com/49179966/144627195-fa48af53-fd1a-4377-85dc-a056f1376d9a.png)
在Windows 11的预览版本中，没有显示“评估副本”和”过期时间“这一部分的内容。
In the preview version of Windows 11, the "evaluation copy" and "expiration time" sections are not displayed.

**Comment by dongle-the-gadget** [comment]
Yeah the expiration is currently not implemented.

**Comment by dongle-the-gadget** [comment]
> It would be nice if the Windows 11 logo icon had a color (such as Microsoft Windows 11's gradient blue).

It quite concerns me about contrast though, since if you use a really deep blue background the Windows 11 logo would be almost invisible. The contrast on the link is already bad.

**Comment by Void48** [comment]
> 

I like the look of this 👍🏻

**Comment by dongle-the-gadget** [comment]
@Void48 I'm not planning to do a redesign of it, add color, or change the framework.

UWP was made with touch in mind, this is just WPF, also WPF doesn't have native support for Mica.

**Comment by dongle-the-gadget** [comment]
@Gaoyifei1011 The latest commits (which is planned to be released as part of Release 2.0) now resolves the icon issue, and should also resolve the weird experience text.

**Comment by dongle-the-gadget** [comment]
Issues listed here should be resolved with Release 2 now!
